defaultCiPipeline {
	platform = ['ubuntu']
	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'sdk-javascript'

	publisher = 'npm'
	dependencyPackageToPublish = ['_build/wasm/node', '_build/wasm/web_webpack']

	codeCoverageTool = 'c8'
	minimumCodeCoverage = 90
}
